apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: daykeeper-attachments
  namespace: daykeeper
  labels:
    app.kubernetes.io/name: daykeeper-api
    app.kubernetes.io/component: storage
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
