coverage:
  paths:
    - "**/coverage.cobertura.xml"
  badge:
    path: badges/coverage.svg

comment:
  enable: true
  hideFooterLink: false

diff:
  datastores:
    - artifact://${GITHUB_REPOSITORY}
